# main menu
[[main]]
name = "Home"
url = ""
weight = 1

[[main]]
name = "About"
url = "about/"
weight = 2

[[main]]
name = "Blog"
url = "blog/"
weight = 3

[[main]]
weight = 5
name = "Policy"
hasChildren = true

  [[main]]
  parent = "Companies"
  name = "Silver Tree Agencies"
  url = "sta"
  weight = 1

  [[main]]
  parent = "Policy"
  name = "Terms & Conditions"
  url = "terms-and-condition/"
  weight = 7

  [[main]]
  parent = "Policy"
  name = "Privacy Policy"
  url = "privacy-policy/"
  weight = 8

  [[main]]
  parent = "Policy"
  name = "FAQ"
  url = "faq/"
  weight = 8
  
[[main]]
name = "Contact"
url = "contact/"
weight = 4


# footer menu
[[footer]]
name = "About"
url = "about/"
weight = 1

[[footer]]
name = "Blog"
url = "blog/"
weight = 2

[[footer]]
name = "Terms & Conditions"
url = "terms-and-conditions/"
weight = 3

[[footer]]
name = "Privacy Policy"
url = "privacy-policy"
weight = 4