#################### default parameters ################################
# favicon
favicon = "images/favicon.png"
# logo
logo = "images/logo.png"
# use `x` with logo_width, example: "100x"
logo_width = "240x"
# logo text will only show when logo is missing.
logo_text = "Technologically Zealous Family"
# OpenGraph / Twitter Card metadata
description = "Technologically Zealous Family, Digital Agency, Software Company and Many more"
author = "Glenville Dixon Jr"
image = "images/logo.png"                # this image will be used as fallback if a page has no image of its own

# footer information
footer_info = "What is Technologically Zealous Family? We are a vibrant startup Digital agency in the Caribbean island of Antigua and Barbuda."

# contact form action
contact_form_action = "https://formspree.io/f/mlezprdr" # contact form works with https://formspree.io

# copyright
copyright = "Copyright © 2022 all rights reserved to Technologically Zealous Family. Designed By [Glenville Dixon Jr](https://glenville.tzfi.page/)"

# custom script on header, example: custom_script= "<script>console.log(\"Hello World\")</script>" 
custom_script = ""

# buy premium popup
buy_premium_popup = true

# Main Sections
mainSections = ["blog"]

# reading time for blog posts
reading_time = true

# contact information
[contact_info]
address = "Bucklies St. Johns, Antigua and Barbuda"
phone = ["+268-776-4380", "+268-784-7341", "+"]
email = ["connect@tzfi.page", "support@tzfi.page", "helpdesk@tzfi.page"]

# imaging processing
[imaging]
# Default JPEG or WebP quality setting. Default is 100.
quality = 100

# Preloader
[preloader]
enable = true
preloader = "images/favicon.png" # use jpg, png, svg or gif format.

# Navigation button
[navigation_button]
enable = true
label = "Contact us"
link = "mailto:connect@tzfi.page"

# cookies
[cookies]
enable = true
expire_days = 7
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"

# call-to-action
[cta]
enable = true
title = "Contact Us Below And Inquire About Our Company And Services"
content = ""
button = "Contact Us"
button_link = "mailto:connect@tzfi.page"

############################# social site ########################
[[social]]
title = "Check our facebook if you are that type of person"
icon = "lab la-facebook-f" # https://icons8.com/line-awesome
link = "https://www.facebook.com/TZFMain"

[[social]]
title = "Check our Behance to see inside the designer minds of the people that run the company"
icon = "lab la-behance"  # https://icons8.com/line-awesome
link = "https://twitter.com/ZealousFamily"

[[social]]
title = "Check out our Linkedin for Updates and Posts"
icon = "lab la-linkedin-in" # https://icons8.com/line-awesome
link = "https://www.linkedin.com/company/tzfi/?viewAsMember=true"

[[social]]
title = "Check out our youtube channel for more content!"
icon = "lab la-youtube" # https://icons8.com/line-awesome
link = "https://www.youtube.com/channel/UC1WxU2xPScVNAvHFh2ppBQg?view_as=subscriber"

[[social]]
title = "Check out our Google Page for important news and upcoming projects, latest pictures and special nuggets"
icon = "lab la-google" # https://icons8.com/line-awesome
link = "https://technologically-zealous-family.business.site/?utm_source=gmb&utm_medium=referral"

[[social]]
title = "Check out our Medium Page for Blogs, upcoming project descriptons, and even more special nuggets"
icon = "lab la-medium" # https://icons8.com/line-awesome
link = "https://tzfifoundation.medium.com/"


